[package]
name = "tracing-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1", features = [] }
log = { version = "0.4", optional = true }

[features]
default = []
log = ["dep:log"]