[package]
name = "example-lib"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
tracing-shared = { path = "../.." }
tracing = "0.1"
log = { version = "0.4", optional = true }

[features]
log = ["dep:log", "tracing-shared/log"]
